theatre:
  default:
    seats_matrix:
      - name: A
        count: 20
        seat_type: normal
      - name: B
        count: 20
        seat_type: normal
      - name: C
        count: 20
        seat_type: normal
      - name: D
        count: 20
        seat_type: normal
      - name: E
        count: 20
        seat_type: normal
      - name: F
        count: 20
        seat_type: normal
      - name: G
        count: 20
        seat_type: normal
      - name: H
        count: 20
        seat_type: normal
      - name: I
        count: 20
        seat_type: normal
      - name: J
        count: 20
        seat_type: normal